# Generated by Django 5.2.4 on 2025-07-24 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the location (e.g., Main Warehouse)', max_length=255, unique=True)),
                ('address', models.TextField(blank=True, help_text='Address of the location', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Quantity of the product available at this location')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='products.product')),
                ('location', models.ForeignKey(help_text='The location of this stock', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.location')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'unique_together': {('product', 'location')},
            },
        ),
    ]
